"""
Invoice Service (Python / Flask)

Generates a small PDF document on demand. Stands in for any
domain-specific worker behind the gateway.

Endpoints:
  GET /generate?name=Alice  -> downloadable PDF
  GET /health               -> {"status": "ok"}
"""

import os
import tempfile
from flask import Flask, request, send_file, jsonify, after_this_request
from fpdf import FPDF

app = Flask(__name__)

PORT = int(os.getenv("PORT", "8081"))


@app.route("/generate")
def generate_invoice():
    name = request.args.get("name", "User")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Service Report: {name}", ln=1, align="C")
    pdf.cell(200, 10, txt="Generated by invoice-service.", ln=2, align="C")

    # Write to a unique temp file rather than cwd so the container's
    # filesystem doesn't slowly fill up across requests.
    fd, tmp_path = tempfile.mkstemp(prefix=f"doc_{name}_", suffix=".pdf")
    os.close(fd)
    pdf.output(tmp_path)

    # Best-effort cleanup once Flask is done streaming the file.
    @after_this_request
    def cleanup(response):
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        return response

    return send_file(tmp_path, mimetype="application/pdf",
                     as_attachment=True, download_name=f"doc_{name}.pdf")


@app.route("/health")
def health():
    return jsonify(status="ok"), 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=PORT)